### ISSUE TITLE
Login v3.0 수정사항

### ISSUE THREAD

**Issue by Yejin-Ha** [A-Womans-Society/alice-diary#121]
Login v3.0 수정사항입니다

**Comment by Yejin-Ha** [comment]
- [ ] 회원가입 시 중복된 ID가 있는지 체크를 못합니다.

**Comment by da11un** [comment]
- [ ] 탈퇴 시 비밀번호 필수인증 기능 없애기

**Comment by melanieing** [comment]
닉네임도 유니크 제약 걸기 (엔티티, UserDto 반영 plz)
