### ISSUE TITLE
Friends v2.0 수정사항

### ISSUE THREAD

**Issue by Yejin-Ha** [A-Womans-Society/alice-diary#122]
Friends v2.0 수정사항입니다

**Comment by Yejin-Ha** [comment]
- [ ] 자기 자신이 검색되는 경우와 추가되는 경우를 막아주세욤!

**Comment by da11un** [comment]
- [ ] 친구 추가 시 id가 아니라 닉네임(구:이름)으로 추가하도록 바꿔야 합니다
(-> 왜냐하면, 소셜 로그인을 한 회원은 id가 google_154646115 이런 식이기 때문이죠!!)

**Comment by melanieing** [comment]
친구 추가 시 닉네임/MBTI 형식이 보이는데, mbti 등록을 안한 사람이면 null로 보여요 이거 해결해야 할 듯!
-> '-'으로 보이게 하면 어떨까요? (다은)
