### ISSUE TITLE
Community ver3.0 보완

### ISSUE THREAD

**Issue by ksoolim** [A-Womans-Society/alice-diary#127]
- [x] 탈퇴회원 게시물은 어떻게? (닉네임을 '알 수 없음'으로 처리) -> 게시물 작성자를 아이디가 아닌 닉네임으로
- [x] 아이디검색도 닉네임 검색으로 바꾸기
- [x] 초대회원 추가 시 기존추가회원은 유지하고 목록 갱신
- [x] 초대회원 없을 때 회원초대해주세요 alert

**Comment by ksoolim** [comment]
- [ ] 친구는 서로 쌍방 친구인 사람만 커뮤니티 초대 가능하도록 수정하기(병합 후)

**Comment by ksoolim** [comment]
- [ ] 탈퇴하면 exist 경로로 이동

**Comment by melanieing** [comment]
공개게시판에서 댓글/답글쓴이한테는 쪽지보내기가 가능한데, 게시물글쓴이한테는 쪽지보내는 기능이 없는건가욥?!

**Comment by melanieing** [comment]
![image](https://user-images.githubusercontent.com/91274798/181292676-3a3cca09-4b4d-4875-9ece-9d935030fd5c.png)
여기 '게시글 상세보기'라는 제목보다 '공개게시판'이라고 하는 게 더 좋지 않을까요??

**Comment by Yejin-Ha** [comment]
- [ ] 나의 커뮤니티 탈퇴 버튼 누르고 confirm창 뜨고 취소 눌러도 커뮤니티가 삭제됩니다
  - 사실 이것저것 해보다가 갑자기 탈퇴된거 같아서 당황스러워요들레이호우

**Comment by Yejin-Ha** [comment]
![image](https://user-images.githubusercontent.com/83754224/181753520-243d204d-ab8e-427b-bab8-16d585ba4d94.png)

회원 목록에 닉네임을 쓰는건 어떨까 생각해보았답니다.jpg

**Comment by Yejin-Ha** [comment]
- [ ] 나의 커뮤니티 돌아다니면서 사이드 메뉴에 내 커뮤니티 다 나오는지 확인 부탁드립니당
