### ISSUE TITLE
Message v3.0 수정 사항

### ISSUE THREAD

**Issue by Yejin-Ha** [A-Womans-Society/alice-diary#135]
Message v3.0 수정 사항입니다.

**Comment by Yejin-Ha** [comment]
- [ ] 사진, 문서 모아보기에서 테이블이 전체 오른쪽 정렬로 나오는데 가운데 정렬이나 왼쪽 정렬 등 이쁘게 맞춰주세욤❤
- [ ] 사진 모아보기 테이블에서 이미지 샘플이 보이도록 수정해주세요🧡

**Comment by melanieing** [comment]
- [ ] 쪽지 주고받는 상대 아이디가 아니라 닉네임이 나오도록 수정 완료
