### ISSUE TITLE
Admin 수정 사항

### ISSUE THREAD

**Issue by ksoolim** [A-Womans-Society/alice-diary#143]
어드민 마지막 수정 필요한 사항들입니다

**Comment by melanieing** [comment]
- [ ] 아이디로 보여주는 걸 전부 다 닉네임으로 바꾸기
- [ ] 모든 페이지에 닉네임 검색기능 추가하기
- [ ] 신고목록에서 개별 신고상세페이지로 넘어가는 페이지 만들기
