### ISSUE TITLE
2차 배포테스트 피드백

### ISSUE THREAD

**Issue by melanieing** [A-Womans-Society/alice-diary#157]
2차 배포테스트 피드백

**Comment by melanieing** [comment]
- [ ] 이메일 인증 페이지 아이디 -> 닉네임으로 변경

**Comment by Yejin-Ha** [comment]
그룹목록에서 특정 친구추가(ex. 분홍색브라우저) 하면 직렬화에러 남.... (절대,,,, 숨겨,,,,)
