### ISSUE TITLE
커뮤니티 게시물 상세 보기 구현

### ISSUE THREAD

**Issue by Yejin-Ha** [A-Womans-Society/alice-diary#16]
커뮤니티에 작성된 게시물의 내용을 상세하게 볼 수 있는 기능을 구현해 주세요.

**Comment by ksoolim** [comment]
0712
- 갑자기 페이징처리오류! 원인은 중괄호^ㅡ^ 괄호와 중괄호를 잘보자
0713 
- 상세보기에서 글 상세글은 num 검색으로 POST 엔티티에서 findById(num)으로 받아와야했고 첨부파일 원본명은 num 검색으로 AttachedFile 엔티티에서 findById(num)으로 받아와야했다 기본인데 못했음;;;
- 다시한번 검토를 위해 테이블 생성부터 다시 시도 중 긴 글의 게시글이 등록이 안되는 것을 발견! 칼럼 조건을 @Column(length = 50000) 요렇게 수정! @melanieing 
- 파일다운로드 무난히 되는 듯 하다가,,, 다운로드 완료가 안된다 오류페이지도 안떠서 원인을 모르겠음..... 강사님의 도움을 받을 예정 ㅠㅠ

**Comment by ksoolim** [comment]
**0713**
- 경로 설정의 문제가 있었다. 다른 참고게시글을 보고 재코딩하니 다운로드 완료! 한글 파일명 깨져서 인코딩 포함! 참고게시글(https://ssdragon.tistory.com/109)
