### ISSUE TITLE
캘린더 v1.0 수정 사항들

### ISSUE THREAD

**Issue by da11un** [A-Womans-Society/alice-diary#38]
버그를 잡으세요. 에프킬라

**Comment by da11un** [comment]
- 일정 등록 시 설정한 색상이 상세 보기 화면에서와 다릅니다.
- 일정 날짜가 +1되어서 보입니다

**Comment by Yejin-Ha** [comment]
- 로그인한 유저의 이벤트만 출력되도록 수정

**Comment by Yejin-Ha** [comment]
- [ ] 로그인이 안된 유저라면 바로 login 화면으로 이동하도록 수정해주세요

**Comment by Yejin-Ha** [comment]
- [ ] 알람을 날짜가 아닌 @일전 이런 형태로 변경하기
