### ISSUE TITLE
검색 기능 구현

### ISSUE THREAD

**Issue by mki1105** [A-Womans-Society/alice-diary#46]
커뮤니티 검색 기능을 구현하세요.

**Comment by ksoolim** [comment]
**0718**
- 게시글이 없을 떄 하단 페이징 블록에 1, 0이라고 뜸 해결하시오.

**Comment by ksoolim** [comment]
**0720**
- JSP 페이징 기법 @PageableDefault 사용으로 Pageable 인터페이스 클래스로 아주 간단하게 구현가능 -> 벗,,, 이유는 모르겠지만 자동 sort 기준이 writer 검색시 필드명을 찾지못함.... (똑같이 잘햇음....ㅜㅜ) 
##############해결(?)############ 그래서 결국 노가다 시전,,, 쿼리문을 각각만들어서 order by 따로 지정 / 그래서 JPA의 findBy(칼럼명)Containing 편리한 메소드 사용못함 ㅠㅠㅠ 속상해
- 내용검색 varchar가 아닌 long으로 자꾸 칼럼지정되서 create 개많이 함 해결및 결론은 우리 노션에있음! 거기 테이블 생성쿼리 참고부탁 ㅠㅠ
