### ISSUE TITLE
댓글 메뉴 활성화(쪽지, 수정, 삭제, 신고) 

### ISSUE THREAD

**Issue by mki1105** [A-Womans-Society/alice-diary#48]
커뮤니티 댓글 메뉴 활성화(쪽지, 수정, 삭제, 신고)를 구현하세요.

**Comment by ksoolim** [comment]
**0721**
- 댓글수정은 다음기회에! :(
- 댓글삭제 -> 자식댓글/ 자식댓없는 부모댓/ 자식댓있는 부모댓 3분류로 나누어야 하는 이슈 발생 ㅠㅠ reply_num & parent_rep_num 비교로 자식댓 유무확인하여 자식댓이 있는 부모댓은 status(alive / dead) enum 칼럼 추가하여 dead 변경 후 status 기준에 따라 '삭제된 댓글입니다'로 댓글 리스트에 표기
