### ISSUE TITLE
회원가입 v1.0 수정 사항들

### ISSUE THREAD

**Issue by da11un** [A-Womans-Society/alice-diary#64]
회원가입 v1.0 수정 사항들입니다.

**Comment by Yejin-Ha** [comment]
입력 형식이 일치하지 않은 채로  submit해도 가입 축하 alert창이 뜸

**Comment by ksoolim** [comment]
- 비밀번호가 변경되지 않음!

**Comment by melanieing** [comment]
✅ 회원가입 폼 html
1. 모든 필수 필드 required, placeholder 설정
2. 에러메시지는 small

✅ pom.xml
1. spring-boot-starter-mail 의존 추가했는지 확인

✅ application.properties
1. spring.profiles.active=local
