### ISSUE TITLE
쪽지함 v1.0 수정 사항들

### ISSUE THREAD

**Issue by da11un** [A-Womans-Society/alice-diary#70]
쪽지함 v1.0 수정 사항들입니다.

**Comment by da11un** [comment]
쪽지가 없을 때 화면에 나오지 않는 경우가 있습니다.
로그인했을 때 쪽지함이 나오도록 구현하시죠;

**Comment by ksoolim** [comment]
- 쪽지함 나가기를 누르면 쪽지함으로 redirect가 되도록 수정해주세요
- 목록에서 쪽지함 삭제가 안됩니다.
- 쪽지함에서 쪽지함 목록으로 가는 버튼이 있으면 좋을것 가탕요!

**Comment by melanieing** [comment]
로그인했을 때 바로 빈 쪽지함이 나오도록 구현완료!!!

**Comment by melanieing** [comment]
💡 쪽지를 자기 자신에게 보내면 불가 alert 뜨고 멈춰야 되는데 submit됨 -> 해결해야 됨

**Comment by melanieing** [comment]
목록에서 쪽지함 삭제 구현 완료
쪽지함에서 쪽지함 목록으로 가는 버튼 만들었음!!
