### ISSUE TITLE
친구목록 v1.0 수정 사항들

### ISSUE THREAD

**Issue by mki1105** [A-Womans-Society/alice-diary#74]
친구목록 v1.0 수정 사항

**Comment by mki1105** [comment]
* 친구목록 번호 1부터 나오게 수정하기
* 대소문자 구분없이 검색가능하도록 수정하기

**Comment by mki1105** [comment]
* 친구 덮임 현상 다시 확인하기

**Comment by Yejin-Ha** [comment]
- 친구 추가 시 일치하는 회원이 없는 경우에도 친구 추가를 누르면 화면이 이동합니다. 이런 현상을 수정하세요
- 친구 추가 모달에서 나갔다가 다시 들어갔을 때 내용이 그대로 유지됩니다. 모달을 새로 켰을 때 내용이 reset되도록 수정하세요.

**Comment by ksoolim** [comment]
- a가 친구로 확인되지 않음 
  - 이유를 모르겠음..
