### ISSUE TITLE
Message page

### ISSUE THREAD

**Issue by Yejin-Ha** [A-Womans-Society/alice-diary#81]
Message page Design

**Comment by Yejin-Ha** [comment]
- [ ] Message box page

**Comment by melanieing** [comment]
- [ ] 전체 쪽지함에서 우측 col 다른 화면으로 바꾸기

**Comment by melanieing** [comment]
- [ ] 쪽지 디테일 카드 헤더에 받는 사람 정보 중 **닉네임**을 프사 오른쪽에 배치

**Comment by Yejin-Ha** [comment]
- [ ] 쪽지 보낸 후 alert 지우기!

**Comment by Yejin-Ha** [comment]
친구면 friendinfo로 이동, 친구 아니면 member로 이동
- 친구인지 controller에서 check
  - 친구 o ->
