### ISSUE TITLE
Community page

### ISSUE THREAD

**Issue by Yejin-Ha** [A-Womans-Society/alice-diary#84]
Community page design

**Comment by Yejin-Ha** [comment]
- [ ] post write form page
- [ ] post view page
- [ ] update post page

**Comment by ksoolim** [comment]
- [ ] 생성 커뮤니티 사이드 메뉴바
- [ ] 방장 톱니바퀴모양 위치
- [ ] 커뮤니티생성화면 엉망진창쓰 ㅜㅜ (글쓰기 화면과 비슷하게 가도 무관)
- [ ] 커뮤니티 전체게시판 -> modal textarea(신고, 쪽지)

**Comment by Yejin-Ha** [comment]
- [ ] 게시물 쪽지 보내기 쪽지랑 형태 통일
