### ISSUE TITLE
Message] 화면단 모든 링크 연결하기

### ISSUE THREAD

**Issue by Yejin-Ha** [A-Womans-Society/alice-diary#98]
Message] 화면단 모든 링크 연결하기

**Comment by melanieing** [comment]
커뮤니티-쪽지함 기능 연결 완료 

- [ ] 댓글/답글 눌러서 쪽지보내기 기능
- [ ] 커뮤니티 생성 시 초대 쪽지 보내기 기능

**Comment by melanieing** [comment]
친구-쪽지함 기능 연결해야 됨
#친구 프로필 상세보기에서 쪽지보내기 기능
